### ISSUE TITLE
AppImage for Linux installs?

### ISSUE THREAD

**Issue by ShadowWarfare** [Librelancer/Librelancer#133]
It would be useful if LibreLancer had an AppImage made available for Linux if you don't know what it is here's the documentation link for the Appimage explanation.

https://docs.appimage.org/user-guide/faq.html

Could this be considered for Linux users?

**Comment by CallumDev** [comment]
A problem I foresee with this is a full SDK librelancer build contains 7 separate binaries, this would require 7 AppImages in order to work normally.

Along with the code changes required to load config files from outside the appimage, this would result in 7 44MiB downloads for the user (with maximum level zstd compression on the squashfs), as opposed to the simple 48MiB .tar.gz available now.

This may be more useful later on when the engine itself is useful standalone, but even then it would be duplication for the server
